NAME : SWETHA V


REGISTER NUMBER : 20MIS0405

In [3]:
# 1.

name = "xyz"
print(name)
age = 19
print(age)


xyz
19


In [11]:
# 2.

X="Datascience is used to extract meaningful insights."
x = X.split()
print(x)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [21]:
# 3. 

def multiplication(x,y):
    z= x*y
    print(z)

In [22]:
multiplication(10,1)

10


In [26]:
# 5.

x = range(1,1000,100)
for n in x:
    print(n)


1
101
201
301
401
501
601
701
801
901


In [28]:
import numpy as np
x = np.array([[1,2,3,4],[8,9,0,1],[1,3,2,4],[4,9,0,8]])
x

array([[1, 2, 3, 4],
       [8, 9, 0, 1],
       [1, 3, 2, 4],
       [4, 9, 0, 8]])

In [29]:
x.ndim

2

In [130]:
# 6. 

import numpy as np
x = np.array([[[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]]])
x              


array([[[[1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1]]]])

In [131]:
x.ndim

4

In [94]:
# 6. 
def Identity(size):
for row in range(0, size):
for col in range(0, size):
    if (row == col):
print("1 ", end=" ")
else:
print("0 ", end=" ")
print()


size = 4
Identity(size)




1  0  0  0  
0  1  0  0  
0  0  1  0  
0  0  0  1  


In [74]:
# 7. 

import numpy as np
x =  np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# 8. 
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

array_sum = array1 + array2
print(array_sum)


[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [101]:
# 9. 

import datetime
import pandas as pd

# initializing date
test_date = datetime.datetime.strptime("01-2-2022", "%d-%m-%Y")


K = 29

date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))


Index(['01-02-2022', '02-02-2022', '03-02-2022', '04-02-2022', '05-02-2022',
       '06-02-2022', '07-02-2022', '08-02-2022', '09-02-2022', '10-02-2022',
       '11-02-2022', '12-02-2022', '13-02-2022', '14-02-2022', '15-02-2022',
       '16-02-2022', '17-02-2022', '18-02-2022', '19-02-2022', '20-02-2022',
       '21-02-2022', '22-02-2022', '23-02-2022', '24-02-2022', '25-02-2022',
       '26-02-2022', '27-02-2022', '28-02-2022', '01-03-2022'],
      dtype='object')


In [110]:
# 10.

import pandas as pd

data = {'Brand':['Maruti','Renault','Hyndai'],
        'Sales':[250,200,240]}
dataframe = pd.DataFrame.from_dict(data)
dataframe

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240